base_url = "/"
compile_sass = true
highlight_code = true
build_search_index = true

title = "AOSC Wiki"
description = "Do in the Know"
languages = [
    {code = "zh", search = true}, 
]

taxonomies = [
    {name = "tags", lang = "en"},
    {name = "tags", lang = "zh"},
]

[extra]
logo = "/img/aosc.png"
logo_text = "Wiki"

[translations]
[translations.en]
zh = "ç®€ä½“ä¸­æ–‡"
description = "Do in the Know"
search_placeholder = "Search AOSC Wiki"
also_available_in = "Also available in:"
on_this_wiki = "On this Wiki:"
subsecs_in_this_sec = "Subsections in this section:"
contents_in_this_section = "Contents in this section:"
categories = "Categories:"
footer_msg = "Copyleft ğŸ„¯ 2011 â€” 2020, Members of the Community"

[translations.zh]
en = "English"
description = "è‡´çŸ¥è€Œè¡Œ"
search_placeholder = "æœç´¢ AOSC Wiki"
also_available_in = "å…¶ä»–è¯­è¨€ï¼š"
on_this_wiki = "ç« èŠ‚ï¼š"
subsecs_in_this_sec = "å­ç« èŠ‚ï¼š"
contents_in_this_section = "æœ¬ç« å†…å®¹ï¼š"
categories = "ç±»åˆ«ï¼š"
footer_msg = "ç‰ˆæƒå±å·¦ ğŸ„¯ 2011 â€” 2020ï¼Œç”±å…¨ä½“ç¤¾åŒºæˆå‘˜ç»´æŠ¤"
